// packages/web-components/src/components/newsletter/unidy-newsletter.tsx
import { Component, h, State, Prop, Event, EventEmitter } from '@stencil/core';
import { UnidyClient } from "@unidy.io/sdk-api-client"

@Component({
  tag: 'unidy-newsletter',
  styleUrl: 'unidy-newsletter.css',
  shadow: true,
})
export class Newsletter {
  @Prop() title: string;
  @Prop() newslettersConfig: { internal_name: string; label: string; checked?: boolean }[] = [];
  @Prop() defaultNewsletterInternalName: string;
  @Prop() submitButtonText: string = 'Subscribe';
  @Prop() emailLabel: string = 'E-mail';
  @Prop() emailPlaceholder: string = 'Enter your email';
  @Prop() apiUrl: string;
  @Prop() apiKey: string;

  @State() email: string = '';
  @State() checkedNewsletters: string[] = [];
  @State() messages: { color: string; text: string, error_identifier: string }[] = [];
  @State() showSuccessCheckmark: boolean = false;

  @Event() success: EventEmitter<any>; // Define the event

  private client: UnidyClient;

  componentWillLoad() {
    this.client = new UnidyClient(this.apiUrl, this.apiKey);

    this.checkedNewsletters = (this.newslettersConfig || [])
      .filter((n) => n.checked)
      .map((n) => n.internal_name);
  }

  private handleSubmit = async (e: Event) => {
    e.preventDefault();
    this.messages = [];

    const payload = {
      email: this.email,
      newsletter_subscriptions: this.checkedNewsletters.length > 0
        ? this.checkedNewsletters.map((newsletter) => ({
          newsletter_internal_name: newsletter,
        }))
        : [{ newsletter_internal_name: this.defaultNewsletterInternalName }],
    };

    const [error, response] = await this.client.newsletters.createSubscriptions(payload);

    if (error) {
      if (error === 'newsletter_error') {
        const errors = response.data?.errors || [];

        let errorMessages = errors.map((error: { error_identifier: string; newsletter_internal_name: string }) => {
          switch (error.error_identifier) {
            case 'unconfirmed':
              return { color: 'red', text: "Email not confirmed", error_identifier: error.error_identifier };
            case 'already_subscribed':
              return { color: 'red', text: "Already subscribed", error_identifier: error.error_identifier };
            case 'invalid_email':
              return { color: 'red', text: 'Invalid email address', error_identifier: error.error_identifier };
            default:
              return { color: 'red', text: 'Unknown error occured', error_identifier: error.error_identifier };
          }
        });

        errorMessages = errorMessages.filter(
          (message, index, self) => index === self.findIndex((m) => m.text === message.text)
        );

        this.messages = [...this.messages, ...errorMessages];
        return;
      }
      if (error === 'rate_limit_exceeded') {
        // TODO: handle rate limit exceeded error

        alert('Rate limit exceeded. Please try again later.');
      }
    } else {
      this.showSuccessCheckmark = true;
      this.success.emit(response.data.created);
    }

    this.email = '';
  };

  private toggleNewsletter(value: string) {
    this.checkedNewsletters = this.checkedNewsletters.includes(value)
      ? this.checkedNewsletters.filter((v) => v !== value)
      : [...this.checkedNewsletters, value];
  }

  render() {
    return (
      <div part="container" class="max-w-lg border">
        <h1 part="heading">{this.title}</h1>
        <slot name="description"></slot>
        <form onSubmit={this.handleSubmit} class="space-y-4">
          <div part="email-input-group">
            <label part="email-input-label">{this.emailLabel}</label>
            <input
              part="email-input"
              required
              placeholder={this.emailPlaceholder}
              value={this.email}
              onInput={(e: any) => (this.email = e.target.value)}
              class="w-full border"
            />
          </div>

          {this.newslettersConfig.map((newsletter) => (
            <label class="flex items-center">
              <input
                type="checkbox"
                value={newsletter.internal_name}
                checked={this.checkedNewsletters.includes(newsletter.internal_name)}
                onChange={() => this.toggleNewsletter(newsletter.internal_name)}
                class="mr-2"
              />
              {newsletter.label}
            </label>
          ))}
          <slot></slot>
          <button
            part="submit-button"
            type="submit"
            class="w-full border"
          >
            {this.submitButtonText}
          </button>

          <div part="error-messages-container" class="text-sm">
            {this.messages.map((message) => (
              <div part={`error-${message.error_identifier}`} class="!mt-1">{message.text}</div>
            ))}
          </div>

          {this.showSuccessCheckmark && (
            <div part="success-checkmark" class="flex items-center justify-center mt-4 text-green-500">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-8 w-8"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </div>
          )}
        </form >
      </div >
    );
  }
}

// examples/sdk_in_react_example/src/UnidyNewsletter.tsx
import { useMemo, useState } from "react";
import { UnidyClient } from "@unidy.io/unidy-sdk/dist/index";

interface NewsletterConfig {
  internal_name: string;
  label: string;
  checked?: boolean;
}

interface UnidyNewsletterProps {
  title: string;
  newsletters_config: NewsletterConfig[];
  submit_button_text?: string;
  email_placeholder?: string;
  apiUrl: string;
  apiKey: string;
}

function UnidyNewsletter({ title, newsletters_config, submit_button_text, email_placeholder, apiUrl, apiKey }: UnidyNewsletterProps) {
  const [email, setEmail] = useState("");
  const [checkedNewsletters, setCheckedNewsletters] = useState(
    newsletters_config.map((n) => (n.checked ? n.internal_name : null)).filter(Boolean),
  );
  const [messages, setMessages] = useState<{ color: string; text: string }[]>([]);

  const client = useMemo(() => new UnidyClient(apiUrl, apiKey), [apiUrl, apiKey]);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>): Promise<void> => {
    e.preventDefault();
    setMessages([]);

    const payload = {
      email,
      newsletter_subscriptions: checkedNewsletters.map((newsletter) => ({
        newsletter_internal_name: newsletter as string,
      })),
    };

    const [error, response] = await client.newsletters.createSubscriptions(payload);

    if (error) {
      if (error === "newsletter_error") {
        const errors = response.data?.errors || [];

        let errorMessages = errors.map((error: { error_identifier: string; newsletter_internal_name: string }) => {
          switch (error.error_identifier) {
            case "unconfirmed":
              return { color: "red", text: `Email not confirmed for ${error.newsletter_internal_name}` };
            case "already_subscribed":
              return { color: "red", text: `Already subscribed to ${error.newsletter_internal_name}` };
            case "invalid_email":
              return { color: "red", text: "Invalid email address" };
            default:
              return { color: "red", text: "Unknown error" };
          }
        });

        errorMessages = errorMessages.filter(
          (message: { color: string; text: string }, index: number, self: { color: string; text: string }[]) =>
            index === self.findIndex((m) => m.text === message.text),
        );

        setMessages((prev) => [...prev, ...errorMessages]);
        return;
      }
      if (error === "rate_limit_exceeded") {
        alert("Rate limit exceeded. Please try again later.");
      }
    } else {
      setMessages((prev) => [...prev, { color: "green", text: "Subscriptions created!" }]);
    }

    setEmail("");
  };

  const toggleNewsletter = (value: string) => {
    setCheckedNewsletters((prev) => (prev.includes(value) ? prev.filter((v) => v !== value) : [...prev, value]));
  };

  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center">
      <div className="max-w-md w-full bg-white p-6 rounded shadow">
        <h1 className="text-2xl font-bold mb-4 text-center">{title}</h1>
        <form onSubmit={handleSubmit} className="space-y-4">
          <input
            required
            placeholder={email_placeholder || "Enter your email"}
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="w-full p-2 border border-gray-300 rounded"
          />

          {messages
            .filter((message) => message.color === "red")
            .map((message, index) => (
              <div key={index} className="text-red-500 text-sm">
                {message.text}
              </div>
            ))}
          {messages
            .filter((message) => message.color === "green")
            .map((message, index) => (
              <div key={index} className="text-green-500 text-sm">
                {message.text}
              </div>
            ))}

          {newsletters_config.map((newsletter) => (
            <label key={newsletter.internal_name} className="flex items-center">
              <input
                type="checkbox"
                value={newsletter.internal_name}
                checked={checkedNewsletters.includes(newsletter.internal_name)}
                onChange={() => toggleNewsletter(newsletter.internal_name)}
                className="mr-2"
              />
              {newsletter.label}
            </label>
          ))}

          <button type="submit" className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700">
            {submit_button_text || "Subscribe"}
          </button>
        </form>
      </div>
    </div>
  );
}

export default UnidyNewsletter;
